2 news stages were added
stembrino/Vertex pull request #3
Opened 2021-04-20 10:53 UTC by MDwaihi

2021-04-20 11:12 UTC, stembrino commented on js/custom-slides.js
> +	  document.getElementById("aboutActive").style.color ="rgb(245, 61, 31)";
You can do those changes, like "aboutActive" color inside updateStageOne function.

2021-04-20 11:16 UTC, stembrino requested changes

2021-04-20 11:16 UTC, stembrino commented on js/custom-slides.js
> +	  // Top Bar Menu colors
The same thing here you can add this part 
  document.getElementById("servicesActive").style.color ="rgb(245, 61, 31)";
	  document.getElementById("aboutActive").style.color ="rgb(230, 230, 230)";
	  document.getElementById("workActive").style.color ="rgb(230, 230, 230)";
	  document.getElementById("contactActive").style.color ="rgb(230, 230, 230)";	
In  updateStageTwo(); to avoid change the framework libreary

2021-04-20 11:34 UTC, stembrino commented
I didn't understand why you don't put the  js/custom-slides.js changes in the menuActive.js
But if you'd like to keep with this just say here that I can approve the merge request

2021-04-20 15:40 UTC, MDwaihi commented on js/custom-slides.js
> +	  document.getElementById("aboutActive").style.color ="rgb(245, 61, 31)";
@stembrino you see the webpage after I did my changes? you can check that everything is fixed but still the problem in the left navigation bar (not the top menu bar) while switching sections. the colors problem I mean. it's a little bit annoying cause the colors of the selected and not-selected bars when we are in section 1 or 3 are different than when we are in section 2 or 4.

2021-04-20 17:31 UTC, stembrino commented on js/custom-slides.js
> +	  document.getElementById("aboutActive").style.color ="rgb(245, 61, 31)";
I think we can fix it, but I accept almost all commits, but there is one that I need you answers to my comments questions. I did the questions here in the code. You can answer the questions to finish the last merge here and then we can continue with the peblems that you are talking about

2021-04-20 19:28 UTC, merged

2021-04-20 19:28 UTC, MDwaihi commented on js/custom-slides.js
> +	  document.getElementById("aboutActive").style.color ="rgb(245, 61, 31)";
I accepted your request. We can proceed I think.

2021-04-24 08:38 UTC, MDwaihi commented on js/custom-slides.js
> +	  document.getElementById("aboutActive").style.color ="rgb(245, 61, 31)";
Any updates?